# Generated by Django 6.0.6 on 2026-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='transcript_file_path',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wants_transcript',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('downloading', 'Baixando video'), ('extracting', 'Extraindo audio'), ('done', 'Concluido'), ('failed', 'Falhou')], default='queued', max_length=30),
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
